import { useState, useEffect } from 'react'
import { useSearchParams, Link } from 'react-router-dom'
import { apiFetch } from '../api/client'
import { motion } from 'framer-motion'

export default function PublicQRVerify() {
  const [searchParams] = useSearchParams()
  const token = searchParams.get('token') || ''
  const [loading, setLoading] = useState(true)
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    async function verify() {
      if (!token) {
        setLoading(false)
        setError('No QR token provided in URL.')
        return
      }
      setLoading(true)
      try {
        let cleanToken = token.trim()
        if (cleanToken.includes('token=')) {
          cleanToken = cleanToken.split('token=')[1].split('&')[0].trim()
        }
        if (cleanToken.startsWith('BPR-SECURED::')) {
          cleanToken = cleanToken.replace('BPR-SECURED::', '').trim()
        }
        const res = await apiFetch(`/qrcodes/${encodeURIComponent(cleanToken)}`)
        setData(res)
      } catch (err) {
        setError(err.message || 'QR code not recognized.')
      } finally {
        setLoading(false)
      }
    }
    verify()
  }, [token])

  const isVerified = data && data.status !== 'not_found' && data.status !== 'error'

  return (
    <div className="min-h-screen bg-slate-950 flex flex-col justify-between text-slate-100 p-4 sm:p-6 selection:bg-emerald-500 selection:text-white">
      {/* Top Header */}
      <header className="max-w-md mx-auto w-full flex items-center justify-between py-3 border-b border-slate-800">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-blue-600 to-emerald-500 flex items-center justify-center font-bold text-white shadow-md text-sm">
            BP
          </div>
          <div>
            <div className="text-xs font-bold text-white tracking-wide uppercase">Barangay Puerto</div>
            <div className="text-[10px] text-slate-400">Official QR Verification Portal</div>
          </div>
        </div>
        <Link to="/login" className="text-xs text-slate-400 hover:text-white font-medium transition-colors">
          Portal Login &rarr;
        </Link>
      </header>

      {/* Main Verification Status Card */}
      <main className="max-w-md mx-auto w-full my-auto py-6">
        {loading ? (
          <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8 text-center space-y-4 shadow-xl">
            <div className="w-16 h-16 rounded-full bg-slate-800 flex items-center justify-center mx-auto text-emerald-400">
              <i className="fas fa-circle-notch fa-spin text-2xl" />
            </div>
            <div className="text-sm font-bold text-white">Verifying QR Authenticity...</div>
            <div className="text-xs text-slate-400">Checking system database records for active relief cycles.</div>
          </div>
        ) : error || !isVerified ? (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-slate-900 border border-red-500/30 rounded-3xl p-6 sm:p-8 text-center space-y-5 shadow-2xl relative overflow-hidden"
          >
            <div className="absolute -top-24 -right-24 w-48 h-48 bg-red-500/10 rounded-full blur-3xl pointer-events-none" />
            
            <div className="w-16 h-16 rounded-2xl bg-red-500/10 border border-red-500/30 flex items-center justify-center mx-auto text-red-400 shadow-inner">
              <i className="fas fa-triangle-exclamation text-3xl" />
            </div>

            <div>
              <div className="inline-block px-3 py-1 bg-red-500/10 border border-red-500/30 rounded-full text-red-400 text-[11px] font-bold uppercase tracking-wider mb-2">
                Unverified QR Code
              </div>
              <h1 className="text-xl font-bold text-white">Not Registered in System</h1>
              <p className="text-xs text-slate-400 mt-1 max-w-xs mx-auto">
                {error || 'This QR code was not generated by the Barangay Puerto Relief System or belongs to an unrecognized token.'}
              </p>
            </div>

            <div className="p-3.5 bg-slate-950/60 rounded-2xl border border-slate-800 text-left text-xs text-slate-400 space-y-1 font-mono">
              <div><strong>Scanned Token:</strong> {token ? `${token.substring(0, 16)}...` : 'None'}</div>
              <div><strong>Verification:</strong> <span className="text-red-400 font-bold">FAILED / UNREGISTERED</span></div>
            </div>

            <Link
              to="/login"
              className="block w-full py-3 bg-slate-800 hover:bg-slate-700 text-white rounded-xl text-xs font-bold transition-all"
            >
              Go to Barangay Portal
            </Link>
          </motion.div>
        ) : (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-slate-900 border border-emerald-500/40 rounded-3xl p-6 sm:p-8 space-y-6 shadow-2xl relative overflow-hidden"
          >
            <div className="absolute -top-24 -right-24 w-48 h-48 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />

            {/* Verification Status Header */}
            <div className="text-center space-y-3">
              <div className={`w-16 h-16 rounded-2xl flex items-center justify-center mx-auto shadow-inner ${
                data.status === 'eligible'
                  ? 'bg-emerald-500/10 border border-emerald-500/40 text-emerald-400'
                  : data.status === 'claimed'
                  ? 'bg-blue-500/10 border border-blue-500/40 text-blue-400'
                  : 'bg-amber-500/10 border border-amber-500/40 text-amber-400'
              }`}>
                <i className={`fas text-3xl ${
                  data.status === 'eligible'
                    ? 'fa-shield-check'
                    : data.status === 'claimed'
                    ? 'fa-circle-check'
                    : 'fa-triangle-exclamation'
                }`} />
              </div>

              <div>
                <div className={`inline-block px-3 py-1 rounded-full text-[11px] font-bold uppercase tracking-wider mb-1 border ${
                  data.status === 'eligible'
                    ? 'bg-emerald-500/15 border-emerald-500/30 text-emerald-400'
                    : data.status === 'claimed'
                    ? 'bg-blue-500/15 border-blue-500/30 text-blue-400'
                    : 'bg-amber-500/15 border-amber-500/30 text-amber-400'
                }`}>
                  {data.status === 'eligible' ? '✅ System Verified QR Code' : data.status === 'claimed' ? '✓ Already Claimed' : '⚠️ Status Attention'}
                </div>
                <h1 className="text-xl font-bold text-white">
                  {data.status === 'eligible' ? 'Authentic Relief Pass' : data.status === 'claimed' ? 'Relief Already Claimed' : data.message}
                </h1>
                <p className="text-xs text-slate-400 mt-1">
                  Issued by Barangay Puerto Relief & Disaster Management
                </p>
              </div>
            </div>

            {/* Beneficiary & Household Details */}
            <div className="p-4 bg-slate-950/80 rounded-2xl border border-slate-800 space-y-3">
              <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                Beneficiary Information
              </div>
              <div className="flex items-center justify-between border-b border-slate-850 pb-2.5">
                <span className="text-xs text-slate-400">Recipient Name</span>
                <span className="text-xs font-bold text-white">
                  {data.member?.fname} {data.member?.lname}
                  {data.member?.is_head && <span className="ml-1.5 px-1.5 py-0.2 bg-blue-500/20 text-blue-400 rounded text-[10px]">Head</span>}
                </span>
              </div>
              <div className="flex items-center justify-between border-b border-slate-850 pb-2.5">
                <span className="text-xs text-slate-400">Household Code</span>
                <span className="text-xs font-mono font-bold text-emerald-400">{data.household?.hh_code || 'N/A'}</span>
              </div>
              <div className="flex items-center justify-between border-b border-slate-850 pb-2.5">
                <span className="text-xs text-slate-400">Purok Area</span>
                <span className="text-xs font-bold text-white">{data.household?.purok_name || 'N/A'}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-400">Active Cycle</span>
                <span className="text-xs font-bold text-white">{data.cycle?.name || 'Active Cycle'}</span>
              </div>
            </div>

            {/* Schedule & Claim Information */}
            {data.cycle && (
              <div className="p-3 bg-slate-800/40 rounded-xl border border-slate-800 text-xs text-slate-300 space-y-1.5">
                <div className="flex items-center gap-2">
                  <i className="fas fa-calendar-check text-emerald-400 w-4 text-center" />
                  <span>Distribution: <strong>{data.cycle.distribution_date || 'Ongoing'}</strong></span>
                </div>
                <div className="flex items-center gap-2">
                  <i className="fas fa-location-dot text-blue-400 w-4 text-center" />
                  <span>Venue: <strong>{data.cycle.claim_address || 'Barangay Puerto Covered Court'}</strong></span>
                </div>
              </div>
            )}

            <div className="text-center pt-1">
              <span className="text-[11px] text-slate-500">
                Official verification record timestamped by Barangay Puerto.
              </span>
            </div>
          </motion.div>
        )}
      </main>

      {/* Footer */}
      <footer className="max-w-md mx-auto w-full text-center text-[11px] text-slate-500 py-3 border-t border-slate-900">
        Barangay Puerto Relief & Incident Distribution Management System (BRIDMS)
      </footer>
    </div>
  )
}
